### ISSUE TITLE
not-eq has unknown reexport

### ISSUE THREAD

**Issue by makepanic** [jmurphyau/ember-truth-helpers#109]
Hi,
I noticed the following due to a warning from embroider.

`app/not-eq` tries to reexport [`notEq` from `addon/not-equal`](https://github.com/jmurphyau/ember-truth-helpers/blob/master/app/helpers/not-eq.js#L1).
`addon/not-equal` only exports [`notEqualHelper`](https://github.com/jmurphyau/ember-truth-helpers/blob/master/addon/helpers/not-equal.js#L3).

This means that there's an export happening that doesn't exist.
Would you be ok with renaming `notEqualHelper` into `notEq`? This should fix the warning.

We could also add an alias export `notEqualHelper` to still be backwards compatible.

If that's ok, I could open a PR.

**Comment by locks** [comment]
Fixed by linked commit!
