### ISSUE TITLE
Update to ember-cli-babel@7

### ISSUE THREAD

**Issue by mehulkar** [jmurphyau/ember-truth-helpers#116]
I include ember-truth-helpers as part of my own addon (let's say `ember-foo-bar`) in `dependencies`. When I install `ember-foo-bar` in an app that has `config/targets.js` set to add include `Safari 13`, `ember serve` breaks. 

I believe this is happening because ember-cli-babel from here is being used as a preprocess because it's in dependencies of `ember-foo-bar`, and that preprocessor has an outdated version of `browserslist` which throws because it doesn't know about Safari 13.

Some workarounds I can think of but haven't tested yet:

- Move `e-t-h` to devDeps of ember-foo-bar
- Update browserlist directly? (not sure if there's a way to do this for something so nested)

But I'm filing this since ember-cli-babel@7 has been out for a while and it probably makes sense to update it here too.

**Comment by rwjblue** [comment]
How does `ember serve` break? Does it throw an error (if so, can you share the stack trace)?

**Comment by SergeAstapov** [comment]
@mehulkar a new version v3.0 of this addon was pushed today, looks like this should be resolved?
