### ISSUE TITLE
`or` doesn't work the same way as `||` in JavaScript

### ISSUE THREAD

**Issue by boris-petrov** [jmurphyau/ember-truth-helpers#141]
```hbs
(or (array) 1)
```

Will return `1`.

```js
[] || 1
```

Will return `[]`.

That's because of [this](https://github.com/jmurphyau/ember-truth-helpers/blob/v3.0.0/addon/utils/truth-convert.js#L9) line. I believe this is confusing to users. It was for me at least. Of course, doing it the other way will be a horrible breaking change so a major version is the least you could do if you decide to change it.

**Comment by sukima** [comment]
I much prefer the behavior it is using now. It aligns with how Ember templates treat empty arrays. Changing it will make it behavior different then how Ember handles empty arrays.

```hbs
{{#each (array) as |item|}}
  This never is handled
{{else}}
  This is handled as the items are empty
{{/each}}

{{#if (array)}}
  Never gets called
{{else}}
  Treated as falsey 'cause the array is empty
{{/if}}
```

**Comment by boris-petrov** [comment]
Well, I guess that's a matter of taste. I personally would prefer to have the same behavior in JS and in HBS for similar things - so `if ([]) ...` to behave the same as `{{if (array) ...}}`. `each` is a bit different as it doesn't have a direct equivalent in JS (I mean the `else` part of course) - so I agree that the current behavior is OK. But for the `if` examples I think that's confusing to people. Besides, you could just write `{{if someArray.length ...}}` and that would work the way you want.

**Comment by boris-petrov** [comment]
So after a [nice discussion](https://discord.com/channels/480462759797063690/485447409296736276/1029629238736846900) I'll close the issue as `ember-truth-helpers` does the correct thing according to the [RFC](https://github.com/emberjs/rfcs/blob/1734f778b0babe4d112be81a3aaf6117975cd3b1/text/0562-add-logical-operators.md#handlebars-definition-of-truthiness) (even though the RFC says that `ember-truth-helpers` does something else - the RFC is wrong in this case).
