### ISSUE TITLE
Update `README` to note that `or`, `and` and `xor` **do** short-circuit

### ISSUE THREAD

**Issue by boris-petrov** [jmurphyau/ember-truth-helpers#143]
```hbs
{{or true (throw "asd")}}
```

This, as of Ember 3.28, shows `true`. `{{or false (throw "asd")}}` throws an exception. So the [section](https://github.com/jmurphyau/ember-truth-helpers#usage) in the README which says that they do not short-circuit should be updated. It was true before, I remember, but it is no longer so.

**Comment by Techn1x** [comment]
:open_mouth: I see! 

A more straightforward way to test this without needing the "throw" helper implemented
```hbs
{{or true (log "NOT CALLED")}}
{{or false (log "CALLED")}}
```

**Comment by Techn1x** [comment]
I've updated the readme here
https://github.com/jmurphyau/ember-truth-helpers/pull/184
