### ISSUE TITLE
Process of creating this addon.

### ISSUE THREAD

**Issue by collegeimprovements** [jmurphyau/ember-truth-helpers#15]
How you created this `addon`? I want to create an addon similar to these for Url and other helpers.
It would be greate if you can guide me a little. I'm very new to `js` and `ember`.

**Comment by btecu** [comment]
https://gist.github.com/kristianmandrup/ae3174217f68a6a51ed5 should be helpful.
You can always just look at the source code too.

**Comment by collegeimprovements** [comment]
Thanks a lot :)
