### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by locks** [jmurphyau/ember-truth-helpers#156]
Hi! I'm reaching out from simplabs as we're interested in taking over maintenance of this addon.

**Comment by ctjhoa** [comment]
@SergeAstapov do you have permisison to add maintainers?

**Comment by SergeAstapov** [comment]
@ctjhoa no I don't have such permissions. on a side note, hope get to some OSS real soon and help with such addons

**Comment by SergeAstapov** [comment]
for history context: #147 converted this addon to Embroider native aka V2 format, need to check if there is anything missing for v4 of this addon to be pushed to npm
