### ISSUE TITLE
Typescript conversion

### ISSUE THREAD

**Issue by bakerac4** [jmurphyau/ember-truth-helpers#163]
Would the owners/mantainers of this repo accept a PR to convert this to typescript? I'd like to be able to have the types from this repo and remove them from `@gavant/glint-template-types`. We use this in every project so it would benefit us greatly (and I believe the wider community?)

But I don't want to start without getting acknowledgment so I know it would eventually be accepted. 

@jmurphyau

**Comment by nlfurniss** [comment]
I image maintainers would be happy to review PRs. My suggestion would be to break it down into multiple PRs instead of one massive one doing the conversion. This makes it much easier and faster to review.
