### ISSUE TITLE
Latest ember depreciations with helpers

### ISSUE THREAD

**Issue by Kilowhisky** [jmurphyau/ember-truth-helpers#18]
FYI latest version of ember yet again screwed with things.

https://github.com/emberjs/ember.js/releases/tag/v1.13.6

`DEPRECATION: Using Ember.HTMLBars._registerHelper is deprecated. Helpers (even dashless ones) are automatically resolved. [deprecation id: ember-htmlbars.register-helper]`

`DEPRECATION: Using `Ember.HTMLBars.makeBoundHelper` is deprecated. Please refactor to using `Ember.Helper` or `Ember.Helper.helper`. [deprecation id: ember-htmlbars.make-bound-helper]`

**Comment by rwjblue** [comment]
@Kilowhisky - Yep, we are on it.  PR swapping to `Ember.Helper` based helpers is in https://github.com/jmurphyau/ember-truth-helpers/pull/12, but there is a little bit of refactoring to do to fix the test suite here.  I'm hopefully going to get this done tonight, but not 100% sure...

**Comment by jmurphyau** [comment]
@rwjblue PR #19 should help with the test refactor you mention - I assume this is the work you're talking about here?

**Comment by rwjblue** [comment]
@jmurphyau - Yep. #12 will solve this (and #19 is required to allow #12 to pass the test suite).

**Comment by jmurphyau** [comment]
@Kilowhisky check out version 1.1.0 - should resolve the deprecation warnings

**Comment by mike-post** [comment]
Confirmed, 1.1.0 solves all the deprecation notices.  Thanks!

**Comment by rwjblue** [comment]
Awesome, thanks for confirming!

**Comment by fadeojo** [comment]
@rwjblue Ember 1.3.18 still complains `Using Ember.HTMLBars._registerHelper is deprecated. Helpers (even dashless ones) are automatically resolved`

**Comment by fadeojo** [comment]
the deprecated code is found in `addon/utils/register-helper.js` line 16 and 26.

**Comment by mike-post** [comment]
@fadeojo Did you upgrade ember-truth-helpers to 1.1.0?

**Comment by rwjblue** [comment]
Ember Data 1.13.8 also had an issue when published, and accidentally contained deprecated register helper calls. Make sure you have 1.13.9 of Ember data.

**Comment by fadeojo** [comment]
@mike-post @rwjblue Thanks. It was ember data with the issue. It's all fixed now.

**Comment by Arkham** [comment]
Also make sure to have the latest version of ember-resolver (0.1.19) in your `bower.json`

**Comment by elwayman02** [comment]
@rwjblue @jmurphyau @Kilowhisky can this be closed?

**Comment by rwjblue** [comment]
Ya, I believe so. Happy to reopen if needed.
