### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by Techn1x** [jmurphyau/ember-truth-helpers#183]
I went to use the glint types as mentioned in the README
https://github.com/jmurphyau/ember-truth-helpers#usage-with-glint

Specifically trying to do lines like `import { or } from 'ember-truth-helpers'` and the types would fail.. I go and check this repo and can see they are indeed exported.

Took me a while to realise that the latest release is 3.1.1 from July 2022 but the glint types etc were added in June 2023 and yet to be released. I can see a lot of other changes going on too... any chance for a beta release or something?

**Comment by Techn1x** [comment]
Apologies if I am being impatient :smile:

**Comment by steveszc** [comment]
Looks like releases are automated on this repo, but its been quite some time since there was a green build.

**Comment by leepfrog** [comment]
I'm going to test out running the `master` branch  to see if the TypeScript types work as expected.

**Comment by leepfrog** [comment]
Looks like it works as expected.  

I have a fork [leepfrog/ember-truth-helpers#installable](https://github.com/leepfrog/ember-truth-helpers/tree/installable) (with a few changes made to make installable from pnpm) if that's something of interest.   (until a release is made!)

**Comment by SergeAstapov** [comment]
@leepfrog FYI fork is not needed, you can simply point to `master-dist` branch https://github.com/jmurphyau/ember-truth-helpers/tree/master-dist, it's pushed via https://github.com/jmurphyau/ember-truth-helpers/blob/master/.github/workflows/push-dist.yml

I don't have permissions for npm, will try to see if someone with permissions will be available.

> Looks like releases are automated on this repo, but its been quite some time since there was a green build.

don't see anything in .github/ folder for that, do you have any pointers about automation?

**Comment by steveszc** [comment]
Oops you are right, the repo is configured with releaseit, but its not fully automated. 
Looks like someone with repo access still needs to manually run `npx release-it`

**Comment by MelSumner** [comment]
@rwjblue @nlfurniss @jmurphyau if you want to add me as a maintainer here and on NPM I would be happy to help with releases. 

This addon is used enough that it might be a good candidate to join the adopted-ember-addon org ([here's how](https://github.com/adopted-ember-addons/program-guidelines)) so we can have a few more active maintainers. Just a thought!

**Comment by SergeAstapov** [comment]
@rwjblue @nlfurniss @jmurphyau could some of you please publish new major v4 to npm?

addon setup was updated with latest [addon-blueprint](https://github.com/embroider-build/addon-blueprint), dependencies updated, CI is happy so we should be good to go.

**Comment by Techn1x** [comment]
Thanks for the v4 beta.0 release!!

**Comment by NullVoxPopuli** [comment]
just tried the beta.0, and the types look good -- any chance for promotion to stable?

**Comment by SergeAstapov** [comment]
@NullVoxPopuli I don't think we could do stable release until #187 fixed. I started working on the fix in #185, not completed yet

**Comment by SergeAstapov** [comment]
[v4.0.0](https://github.com/jmurphyau/ember-truth-helpers/releases/tag/v4.0.0) has been published
