### ISSUE TITLE
[QUESTION] `ember-source` compat

### ISSUE THREAD

**Issue by bertdeblock** [jmurphyau/ember-truth-helpers#194]
The README says v3.28 is supported, but `ember-truth-helpers` has a peer dependency on `ember-source >=4.8.4` [here](https://github.com/jmurphyau/ember-truth-helpers/blob/master/packages/ember-truth-helpers/package.json#L66).
Which one of the two is correct?

**Comment by SergeAstapov** [comment]
@bertdeblock Thanks for highlighting this! readme should be correct one as [we run tests for 3.28 in CI](https://github.com/jmurphyau/ember-truth-helpers/blob/master/.github/workflows/ci.yml#L94) and we added [`ember-functions-as-helper-polyfill` just for <=4.5 support](https://github.com/jmurphyau/ember-truth-helpers/blob/master/packages/ember-truth-helpers/package.json#L35C6-L35C40)

**Comment by bertdeblock** [comment]
Thanks @SergeAstapov!
