### ISSUE TITLE
May have a bug defining the helpers

### ISSUE THREAD

**Issue by juanesarango** [jmurphyau/ember-truth-helpers#2]
I think you may have a bug. I wasn't able to fix. I'm getting this error when trying to use ember-truth-helpers as an addon of ember-cli:

"uncaught type error: cannot read property '_registerhelper' of undefined"

Specifically here in the 24 line in the file register-helper.js:

function registerHelper(name, helperFunction) {
    if (Ember['default'].HTMLBars._registerHelper) {
        if (Ember['default'].HTMLBars.helpers) {
...

I'm using the latest version of ember-cli 0.1.15

**Comment by jmurphyau** [comment]
"cannot read property '_registerhelper' of undefined"
or
"cannot read property '_registerHelper' of undefined"

That would suggest to me you don't have HTMLBars? What version of Ember are you using? Do you have 'Ember.HTMLBars' available to you on the page?

**Comment by jmurphyau** [comment]
@juanesarango are you still seeing this issue?

**Comment by juanesarango** [comment]
@jmurphyau sorry I didn't give a feedback before. But you may be right and my problem was with htmlbars. With that I got some other issues that took me some time to fix, but finally I could make it work. 

Thank you for your fast response!
