### ISSUE TITLE
How to use in ember-cli app?

### ISSUE THREAD

**Issue by swelther** [jmurphyau/ember-truth-helpers#22]
Hi dudes,

most likely this is a very silly question, I apologize for it.

I try to use these awesome helpers in a ember-cli app, but I have "issues".

Added this into my bower.json

```
    "ember-truth-helpers": "0.0.5"
```

and run npm install. And now? Does ember-cli autoload the helper classes? Do I have to import something in my `Brocfile.js`? Or must I import the helpers somehow? Would be cool to have some short startup howto :)

**Comment by trisrael** [comment]
Try `ember install ember-truth-helpers` - it should then be added to
package.json which is for node modules while bower.json loads bower
components

**Comment by swelther** [comment]
Arg that was it! Thank you very much! Sometimes it's too easy and one does not see the solution.

I close this as resolved, thx again :+1:
