### ISSUE TITLE
How to compare mulitple condition

### ISSUE THREAD

**Issue by plimeyepea** [jmurphyau/ember-truth-helpers#24]
{{if ( or (not-eq a b) (not-eq a b) ) }}
This is the format I'm presuming that would work if I wanted to check two things within an or statement, but this breaks my build and left me with a blank page. Is there another format I can try?

**Comment by Keeo** [comment]
Did you try ```{{if (or (not-eq a b) (not-eq a b))}}```?

**Comment by plimeyepea** [comment]
That is exactly what I did, but it doesn't seem to like it very much.

**Comment by Keeo** [comment]
Can you try ```{{if (or (not-eq true true) (not-eq false true)) 'hello'}}```? This has to work.

**Comment by jmurphyau** [comment]
you could try `(not (eq a b) (eq c d))`?

**Comment by rwjblue** [comment]
@plimeyepea - Can you express the logic in JS so that we can properly understand what you are trying to do?

**Comment by plimeyepea** [comment]
I was trying to check to see if my currentRouteName is a certain route. So there's two routes I needed to check:
 ` {{#if (or (not-eq currentRouteName "index") (not-eq currentRouteName "signup")}}
    {{partial 'navigation'}}
  {{/if}}`

However, when I added in the second (not-eq ... "signup"), it breaks my application.

**Comment by bekzod** [comment]
I think something like this will be useful (not sure about `not-any`) 
```handlebars
(or (eq color 'red') (eq actionType 'green') (eq actionType 'yellow')) 
=> 
(any color 'red' 'green' 'yellow')

(or (eq-not color 'red') (eq-not color 'green') (eq-not color 'yellow')) 
=>
(not-any actionType 'all'  'snapshot' 'yellow')```

**Comment by bekzod** [comment]
and `not-any`
```handlebars
(and (not-eq color 'red') (not-eq actionType 'green') (not-eq actionType 'yellow')) 
=> 
(not-any color 'red' 'green' 'yellow')
```

**Comment by rrussell** [comment]
This feature will be really useful, some like that:
```
{{#if (or (eq a b c) (not-eq c d) (gt f g))}}
  {{ model.var }}
{{/if}}
```
etc...

**Comment by jevanlingen** [comment]
@plimeyepea: You missed one parenthese at the end, that's why it broke your application!

One parenthese to close the not-e=> So in full:
 
```javascript
{{#if (or (not-eq currentRouteName "index") (not-eq currentRouteName "signup"))}}
    {{partial 'navigation'}}
{{/if}}
```

**Comment by sales** [comment]
+1

**Comment by jmurphyau** [comment]
I just added a test that demonstrates that this works

**Comment by tinyweasel** [comment]
{{#if (and (or trueProperty falseProperty) (not falseProperty)}} does not work correctly. Should come out true but it's false.

**Comment by darrenw-npi** [comment]
> {{#if (and (or trueProperty falseProperty) (not falseProperty)}} does not work correctly. Should come out true but it's false.

That is also missing a closing parenthesis
