### ISSUE TITLE
A new `is-empty` helper should be added

### ISSUE THREAD

**Issue by devinus** [jmurphyau/ember-truth-helpers#26]
This should use the `Ember.isEmpty` function, and consider changing `truthConvert` to no longer be falsy for empty arrays. That's not how JS works, and truth helpers aren't block helpers. Consider encourage users to use `(is-empty value)` or `(not (is-empty value))` to check arrays. This change would require a semver major bump.

**Comment by rwjblue** [comment]
I think adding is-empty seems fine, but I'm not convinced that truthConvert should be changed. Frankly, the idea that this isn't how JS works doesn't really hold much sway to me. HBS is not JS, and Ember fundamentally considers empty arrays as falsey in HBS.

**Comment by adjohnson916** [comment]
+1 @rwjblue What's the alternative right now for composing empty checks with the other truth helpers?

**Comment by btecu** [comment]
@adjohnson916 If you know you always have an array object (even empty) `{{unless myArray.length}}` if not, you'll have to chain a check for the array `{{if (and myArray myArray.length)`

**Comment by adjohnson916** [comment]
@rwjblue @btecu I've answered my own question about how to handle this currently by adding new unit tests in #27.

**Comment by devinus** [comment]
I want to pick this up and add it if somebody is not already working on it.

**Comment by drewclauson** [comment]
:+1: on the is-empty using Ember.isEmpty().  I would look into it myself, but haven't done anything with addons quite yet. :-)

**Comment by cmackenz** [comment]
It would be nice if this also checked for empty objects `{}`

`Ember.isEmpty` returns `false` when checking `{}` so I had to create a helper that checked the length of my `object`'s key length. eg., `Object.keys(myObject).length === 0` returns `true`.
