### ISSUE TITLE
modulo helper

### ISSUE THREAD

**Issue by AndersDJohnson** [jmurphyau/ember-truth-helpers#29]
Have you considered a modulo helper? Useful for even/odd on array indexes. I'd imagine something like `{{if (mod i 2 0)}}` representing `if (i % 2 === 0)`, and/or shorthand `{{if (mod i)}}` to return truthy `1` or `true` (for odd) and falsy `0` or `false` (for even). I could submit a PR if you might accept it.

**Comment by jeffrey008** [comment]
Adding mod helper is a good idea, but I am wondering if we should put mod helper into ember-truth-helpers. To me, ember-truth-helpers should only return boolean instead of numbers. 
If we can a addon called 'ember-math-helpers' then that would be great. After that we can use something like this : `{{if (eq (mod 10 2) 0)}}`

**Comment by adjohnson916** [comment]
@jeffrey008 Yes, this would broaden scope slightly. What about the simple case of `(mod i)` representing `mod(2)` returning just `true`/`1` or `false`/`0`? Or maybe call them `(even i)` and `(odd i)`? Still, I can see if you don't want in this module.

**Comment by jeffrey008** [comment]
Good idea. Here is my implementation of the helper `is-even`
```javascript
export function isEvenHelper(params) {
  if (type of params[0] !== number){
    Ember.assert(`Expected number: get ${typeof params[0]} instead`);
 } 
  return params[0] % 2 === 0;
}
```
Anyway this is just the first draft of the function, so feel free to modify it.
Also I am wondering if we need a `is-odd` helper, although we can use the result of is-even to know it is odd or not, there may be a case where the params is not integer.

**Comment by Turbo87** [comment]
please note that a `mod` helper is already a part of https://github.com/shipshapecode/ember-math-helpers so there is probably no need to recreate it here too

**Comment by rwjblue** [comment]
Makes sense!
