### ISSUE TITLE
Cascade helper lookup for addon developers

### ISSUE THREAD

**Issue by ksnyde** [jmurphyau/ember-truth-helpers#31]
I'd like to package this addon with some of my addons in a way that consumers of my addon don't also need to install this dependency. Is this possible? I had thought that including it as a "dependency" rather than just a "devDependency" would be all that's needed but that appears not the be the case.

**Comment by rwjblue** [comment]
That is correct. Having this be a dependency is all that is required. 

If that doesn't work, something else is going on.

**Comment by ksnyde** [comment]
Ok thanks Robert. I'll close this and take another look.

**Comment by rwjblue** [comment]
Feel free to reopen with a demo of the problem if you do find an issue.

**Comment by ksnyde** [comment]
Oh just to be sure, the same logic applies to an addon using addon, right? I'm assuming `npm`'s recursion take care of all this for me.

**Comment by rwjblue** [comment]
Yep, every consumer would still need to follow the deps pattern...
