### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by haldiggs** [jmurphyau/ember-truth-helpers#33]
is his helper still viable? the build is broken.

**Comment by skywalkerx86** [comment]
I'm having the same problem. I installed ember-truth-helpers and getting build failed:

Error: Parse error on line 3:
...as |item|}}	{{#if eq(
-------------------------^

**Comment by workmanw** [comment]
@skywalkerx86 I don't believe you can use truth helpers in that way. Because they're really subexpressions, I think the `eq` has to come after the paren. Example:

```javascript
{{#each items as |item|}}
  {{#if (eq item.number 0)}}
    ...
  {{/if}}
{{/each}}
```

**Comment by rwjblue** [comment]
Correct. Thanks @workmanw!

**Comment by skywalkerx86** [comment]
Oh wow, looked at it for so long and didn't see that, thanks
