### ISSUE TITLE
Not working in Ember 2.4.2

### ISSUE THREAD

**Issue by offirgolan** [jmurphyau/ember-truth-helpers#34]
ember: 2.4.2
ember-cli: 2.4.2
ember-truth-helpers": ^1.2.0

```hbs
{{#if (and foo bar)}}
  foo + bar
{{/if}}
```

![screen shot 2016-03-17 at 11 18 14 am](https://cloud.githubusercontent.com/assets/575938/13856393/2d51f472-ec32-11e5-99c6-32eb7cf0fa51.png)

**Comment by rwjblue** [comment]
Should work. I can't think of a change in 2.x that would cause this. Can you create a reproduction?

**Comment by offirgolan** [comment]
Hmmm this is quite strange. In the current source, there is the following rule:

```js
if(Ember.Helper) return;
```

But when I look at the source via chrome debugger that check doesnt exists

```js
function registerHelper(name, helperFunction) {
		if (_ember['default'].HTMLBars._registerHelper) {
			if (_ember['default'].HTMLBars.helpers) {
				registerHelperIteration1(name, helperFunction);
			} else {
				registerHelperIteration3(name, helperFunction);
			}
		} else if (_ember['default'].HTMLBars.registerHelper) {
			registerHelperIteration2(name, helperFunction);
		}
	}
```

I've done a clear cache + hard reset, cleared npm cache, re-installed dependencies and still no luck.

**Comment by rwjblue** [comment]
Can you provide a repro please. Also, tell me your chrome version (there is a recent super annoying and crazy big with helpers + chrome 49/50). 

Also, does this repos test suite fail for you on 2.4?

**Comment by offirgolan** [comment]
Repo is actually internal. Im getting the same error in Firefox as well :cry: 
Chrome Version: 49.0.2623.87 (64-bit)

Ill run the tests and report back

**Comment by offirgolan** [comment]
Just ran tests on Ember v2.4.2 and they all passed but still having the same issue on my end. These are my current dependencies

```json
{
    "abbrev": "1.0.7",
    "babel-plugin-jscript": "1.0.4",
    "bower": "^1.7.7",
    "broccoli-asset-rev": "^2.4.2",
    "broccoli-merge-trees": "^1.1.1",
    "broccoli-static-compiler": "^0.2.2",
    "debounce-query-params": "^0.0.2",
    "ember-ajax": "^2.0.0-beta.2",
    "ember-bootstrap-datetimepicker": "^1.0.2",
    "ember-can": "0.8.0",
    "ember-cli": "2.4.2",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-blanket": "^0.9.1",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-document-title": "^0.3.1",
    "ember-cli-flash": "^1.3.14",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-less": "^1.5.3",
    "ember-cli-mirage": "^0.1.11",
    "ember-cli-moment-shim": "1.0.0",
    "ember-cli-nvd3": "^0.0.8",
    "ember-cli-pretender": "^0.5.0",
    "ember-cli-qunit": "^1.3.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-composable-helpers": "0.19.0",
    "ember-cp-validations": "^2.6.0",
    "ember-data": "^2.4.0",
    "ember-disable-prototype-extensions": "^1.0.0",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-feature-flags": "^2.0.1",
    "ember-infinity": "0.2.2",
    "ember-inflector": "^1.9.4",
    "ember-light-table": "^0.1.2",
    "ember-load-initializers": "^0.5.1",
    "ember-lodash": "^0.0.6",
    "ember-moment": "6.0.0",
    "ember-power-select": "0.9.3-beta.2",
    "ember-resolver": "^2.0.3",
    "ember-select-2": "^1.3.0",
    "ember-tooltips": "^0.5.8",
    "ember-truth-helpers": "^1.2.0",
    "loader.js": "^4.0.1",
    "moment": "^2.12.0",
    "moment-timezone": "^0.5.0",
    "morgan": "^1.7.0",
    "shelljs": "^0.6.0",
  }
```

**Comment by rwjblue** [comment]
What does:

    npm ls ember-truth-helpers

Show?

I suspect you have two versions of ember-truth-helpers at play, and the older one (from before the guard you mentioned above) is present and processed after the current one (which means the helper being used would be the incorrect one).

**Comment by offirgolan** [comment]
Ah. Looks like some internal addon is dependent on v0.0.5 which might be
getting pulled in. Ill try to resolve it tomorrow and see if it fixes it.
Thanks Rob :D


Thanks,
Offir Golan
