### ISSUE TITLE
Uncaught TypeError: Cannot read property '_registerHelper' of undefined

### ISSUE THREAD

**Issue by aranaravi** [jmurphyau/ember-truth-helpers#4]
in register-helper.js i am getting the Uncaught TypeError: Cannot read property '_registerHelper' of undefined why this happening i am using ember-cli version 0.1.12 and handlebars 2.0.0 is there any any exclusive package i need to install, apart from you addon.

**Comment by jmurphyau** [comment]
It's for HTMLBars not Handlebars.. Looks like Ember.HTMLBars is not available to you which is why you get that error

**Comment by aranaravi** [comment]
@jmurphyau ok thanks for the response, is there any possible way to do like this in handlebars with ember cli.
