### ISSUE TITLE
npm package published with engine: "ember-cli-app-version"

### ISSUE THREAD

**Issue by kitsunde** [jmurphyau/ember-truth-helpers#46]
Extremely unimportant detail, but it's not in `package.json` but it's on npm:

``` bash
$ npm show ember-truth-helpers engines
{ node: '>= 0.10.0', 'ember-cli-app-version': '1.0.0' }
```

It also makes yarn 😞 :

```
$ yarn
yarn install v0.16.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning ember-truth-helpers@1.2.0: The engine "ember-cli-app-version" appears to be invalid.
```

**Comment by btecu** [comment]
I'm also getting this warning.

**Comment by leizhao4** [comment]
Same here.

**Comment by jmurphyau** [comment]
Does anyone know what would cause this or how to fix it?

**Comment by btecu** [comment]
@jmurphyau it has been already fixed in [this commit](https://github.com/jmurphyau/ember-truth-helpers/commit/c43ef8fc576a998fea5c039516df9080481dd21a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L17).
You just need to release a new version.

**Comment by jpadilla** [comment]
Confirmed v1.3.0 fixes this.

**Comment by lolmaus** [comment]
:bow:
