### ISSUE TITLE
Can't import helper functions to use functions from Components or Controllers

### ISSUE THREAD

**Issue by dehuszar** [jmurphyau/ember-truth-helpers#50]
It would be really cool to be able to access these functions from my component logic rather than having to write new, redundant helpers.

Can the library be updated to export each of the helper functions so that I can import them like so:

`import { ltHelper } from 'ember-truth-helpers/helpers/lt';`

would allow me to access functions like `ltHelper` in my js code?

**Comment by rwjblue** [comment]
> Can the library be updated to export each of the helper functions so that I can import them like so:

It is already structured this way, the exact import that you pasted should work...

**Comment by dehuszar** [comment]
It does not.

I get the following when trying to access ltHelper in my code:
```
Uncaught ReferenceError: ltHelper is not defined
    at eval (eval at evaluate (:85:21), <anonymous>:1:1)
    at Class.<anonymous> (https://0.0.0.0:4200/assets/skyspecs-portal-fe.js:551:7)
    at ComputedPropertyPrototype.get (https://0.0.0.0:4200/assets/vendor.js:27102:28)
    at Object.get (https://0.0.0.0:4200/assets/vendor.js:32009:19)
    at RootPropertyReference.compute (https://0.0.0.0:4200/assets/vendor.js:25107:26)
    at RootPropertyReference.value (https://0.0.0.0:4200/assets/vendor.js:24974:45)
    at ArrayIterable.iterate (https://0.0.0.0:4200/assets/vendor.js:24730:26)
    at IterationArtifacts.isEmpty (https://0.0.0.0:4200/assets/vendor.js:54789:58)
    at IterablePresenceReference.value (https://0.0.0.0:4200/assets/vendor.js:59190:36)
    at ReferenceCache.initialize (https://0.0.0.0:4200/assets/vendor.js:55366:52)
    at ReferenceCache.peek (https://0.0.0.0:4200/assets/vendor.js:55340:29)
```

**Comment by dehuszar** [comment]
Putting `const ltHelper = require('ember-truth-helpers/helpers/lt').ltHelper;` in it's place _does_ work... technically.

**Comment by rwjblue** [comment]
> It is not working for me.

This is surprising to me.  Can you whip up a demo repo that I can clone and check?

**Comment by dehuszar** [comment]
Sure!  https://github.com/dehuszar/importTest

Here's what I'm finding.  It turns out I can actually console out the function, but if I attempt to access the same var from a breakpoint, it gives me the message above.

**Comment by Turbo87** [comment]
@dehuszar the helpers in this addons are actually *very* simple (e.g. https://github.com/jmurphyau/ember-truth-helpers/blob/master/addon/helpers/lt.js#L9). I'm not sure why you would want to import the `lt` helper to run `lt([a, b])` if you could just check `a < b` 🤔

**Comment by dehuszar** [comment]
Because there's value in not reusability and composability, and Ember helpers can be very useful in this way.  I get that lt([a, b]) is a short snippet, but by that logic, why have a helper at all?  Just create new comparison tools in all your controllers or components.  Voila!

I was just trying to do something, that I thought was doable and it wasn't working as expected.

**Comment by Turbo87** [comment]
> why have a helper at all?

because there is no `<` operator in Handlebars and helpers are primarily meant to be used in templates

**Comment by dehuszar** [comment]
Primarily, but not exclusively.  If I have to recreate the exact functionality of what a helper is doing as a controller or component function, then the helper is no longer DRY, reusable code, but duplicative code.

In the Ember slack channel I asked if Ember allowed for loading helper functions into other modules.  @rwjblue answered that it should and recommended that I create a ticket here so we could look into what was happening.  So that's what I did.

If the answer is `won't fix`, that's fine.
