### ISSUE TITLE
`and` helper should short-circuit

### ISSUE THREAD

**Issue by jrforrest** [jmurphyau/ember-truth-helpers#58]
It seems like the `and` helper should short circuit, so using methods or computed props as the arguments does not cause the rightmost expressions to be evaluated if the left evaluates to false.  This behavior would be more consistent with how JS works.

This came up in our application due to evaluation of computed properties on one of our models causing unnecessary network fetches.  We hoped to prevent these with short-circuiting logic but were surprised to find that even when the first expression evaluated to false the second was still called.

We reproduced this behavior in the twiddle below.

Twiddle: https://ember-twiddle.com/cc9681fd51fe0c2505ac62781dbd41a0?openFiles=templates.application.hbs%2C

**Comment by Turbo87** [comment]
@jrforrest due to the way helpers work in Ember this is simply not possible. helpers are essentially just functions and any parameter that you pass into a function needs to be evaluated before being able to call the function, and the same is true for helper in Ember.

**Comment by rwjblue** [comment]
Thanks for explaining @Turbo87
