### ISSUE TITLE
I'm concerned about size. Is there a "tree-shaking" like option?

### ISSUE THREAD

**Issue by ghost** [jmurphyau/ember-truth-helpers#59]
I know other libraries (like https://github.com/DockYard/ember-composable-helpers#configuration) offers this.

Can we have something like that?

I need just some helpers and I care about size of my .js files.

**Comment by Turbo87** [comment]
there is no such thing built into the addon at this point and the addons isn't actually that larger either so I'm not sure if it would actually be worth the custom-built solution. feel free to come up with a pull requests that implements it though! :)

**Comment by locks** [comment]
The upcoming version in the v2 addon format will address this.
