### ISSUE TITLE
Use truth helpers in unit tests

### ISSUE THREAD

**Issue by lai** [jmurphyau/ember-truth-helpers#6]
I run `ember test` to unit test my Ember CLI project and it seems truth helpers cannot be found. After search around, I added `helper:eq` to my unit test like this
```
moduleForComponent('x-component', {
  // specify the other units that are required for this test
  // needs: ['component:foo', 'helper:bar']
  needs: ['helper:eq']
});
```
Now I get 
```
beforeEach failed on it renders: Attempting to register an unknown factory: `helper:eq`
```
Is there a recommended way to register truth helpers for testing?

**Comment by lai** [comment]
I also tried
````
import truthHelpersInitializer from '../../node_modules/ember-truth-helpers/app/initializers/truh-helpers';
```
with `truthHelpersInitializer.initialize();`
right before `application.injectTestHelpers();`
Still not doing anything. Any ideas?

**Comment by jmurphyau** [comment]
You have to import each helper you want before your tests.. if you look here [here](https://github.com/jmurphyau/ember-truth-helpers/blob/master/tests/unit/helpers/equal-test.js#L10) you can see how I do it. I'm not sure how else to do it but if you find a better way do let me know (:

**Comment by lai** [comment]
Registering each helper works but it's a lot of repetitive setup. This seems less than ideal.

**Comment by lai** [comment]
Thanks for suggesting the solution. I'll close this now.
