### ISSUE TITLE
Performances using plugin like ember-truth-helpers instead of just the Ember default way

### ISSUE THREAD

**Issue by ghost** [jmurphyau/ember-truth-helpers#60]
If I use this plugin: `https://github.com/jmurphyau/ember-truth-helpers`

with many, let's say,

`{{#if (eq model.beautiful true) }}`

or

`{{#if (or (eq model.beautiful true) (eq model.crazy true) ) }}`

what is Ember creating in background? The same javascript works of computedProperties like these:

`isBeautiful: Ember.computed.equal('model.beautiful', true);` and so on?

If I have 30 computedProperty (Ember macros and custom ones) it's better to use this plugin or the default Ember way?

I'm wondering because in some templates I can have something like this many many times!:

`{{#if (or (eq model.beautiful true) (eq model.crazy true) ) }}`

instead of just this one:

`{{#if isBeautifulOrCrazy }}`

What is the best solution in terms of performances?

**Comment by Turbo87** [comment]
it depends ™

**Comment by jevanlingen** [comment]
Your question has already been asked at [Ember.js Discussion Forum](https://discuss.emberjs.com/t/ember-truth-helper-vs-computed-property/9041) two years ago.

According to @rwjblue, it does not matter much:

> Helper invocations have the same caching characteristics as CP's, they will only be invalidated (and their 'compute' function called) when incoming attrs change.

Of course, Ember has changed a lot internally, so maybe this info is a little bit old dated.

**Comment by rwjblue** [comment]
Nope, same answer seems good to me still. 😄

**Comment by locks** [comment]
Since this isn't a technical problem but a question that has been answered in the linked resource, I'm closing the issue.
