### ISSUE TITLE
Compatibility with Ember 2.15

### ISSUE THREAD

**Issue by jwlawrence** [jmurphyau/ember-truth-helpers#69]
I just bumped ember-cli to 2.15.1 and am getting some test failures that I think are related to this addon. I'm using ember-truth-helpers@^1.3.0. I'm seeing failures like these:

"SYNTAX ERROR: #if requires a single argument"

The only thing that looks at all out of the ordinary is a line that resembles this:

`{{#if (and foo (eq bar baz))}}`

Can you verify if this is supported with the new version of glimmer that ships with 2.15?

**Comment by rwjblue** [comment]
Yep, should work fine with 2.15. Happy to try to help debug if you can give us a reproduction case.

**Comment by jwlawrence** [comment]
Thanks @rwjblue I realized after I filed this that the travis build was passing on release, sorry about that. Wish I could give you a reproduction case, but ruling truth helpers out, it's likely an issue in one of our other 2400 tests that is causing a cascade of errors to pop up :) Thanks for responding.
