### ISSUE TITLE
Add bool helper

### ISSUE THREAD

**Issue by erichonkanen** [jmurphyau/ember-truth-helpers#76]
In a form I have an attribute that relies on the existence of a property:

` readonly=(if card true)`

would it make sense to have a short-cut in this lib such as `readonly=(bool card)`?

**Comment by jmurphyau** [comment]
I like this idea

Feel free to open a PR

**Comment by erichonkanen** [comment]
@jmurphyau https://github.com/jmurphyau/ember-truth-helpers/pull/83
