### ISSUE TITLE
Does not work: {{ some-component disabled=(not someModel.isDirty) }}

### ISSUE THREAD

**Issue by lolmaus** [jmurphyau/ember-truth-helpers#8]
So I'm trying to use ember-truth-helpers with this addon: [ember-cli-async-button](https://github.com/dockyard/ember-cli-async-button).

It is a simple component that has a `disabled` property bound to an attribute.

This works as expected:

```handlebars
Component disabled: {{ async-button disabled=true }}
Component disabled: {{ async-button disabled=(not false) }}

Component enabled: {{ async-button disabled=false }}
Component enabled: {{ async-button disabled=(not true) }}
```

Bot then I've got an Ember Data model. This also works fine:

```handlebars
Displays "false" or "true": {{ model.isDirty }}

Component enabled or disabled depending on `isDirty` state:
{{ async-button disabled=model.isDirty }}
```

Now, i'm putting `model.isDirty` into the `not` subexpression, and suddenly it's not working!

```handlebars
Displays "false" or "true": {{ model.isDirty }}

Component always enabled, regardless of `isDirty` state:
{{ async-button disabled=(not model.isDirty) }}
```

![dafuq](http://cdn2.business2community.com/wp-content/uploads/2014/06/thumb.jpg)

**Comment by jmurphyau** [comment]
I'll take a look..

I see you've got:

    Displays "false" or "true": {{ model.isDirty }}

Try also adding:

    Displays "false" or "true": {{ not model.isDirty }}

Make sure that displays what you expect.. It will narrow down the issue a bit more

**Comment by lolmaus** [comment]
`{{ not model.isDirty }}` works as expected.

**Comment by lolmaus** [comment]
I have experienced the same problem with an `if` subexpression, without `ember truth helpers`.

And I was unable to reproduce the problem with a blank component.

Looks like it's a problem of ember-cli-async-button.

**Comment by lolmaus** [comment]
https://github.com/dockyard/ember-cli-async-button/issues/41
