### ISSUE TITLE
is-in helper

### ISSUE THREAD

**Issue by Techn1x** [jmurphyau/ember-truth-helpers#82]
I have my own helper called `is-in` (and inversely, `not-in`)
```handlebars
{{#if (is-in messageType 'ignition_on' 'ignition_off' 'idling_start' 'idling_end')}}
 {{!-- messageType is equal to one of the given items --}}
{{/if}}
```

Is this worth adding to ember-truth-helpers? I will make a PR for it, but only if it's worth adding (I don't want to make a PR that just sits unmerged)

If so, I'll probably change it to something like this, so that it's always clear what item is the main element
`{{#if (is-in item=messageType 'ignition_on' 'ignition_off' 'idling_start' 'idling_end')}}`

Thoughts?

**Comment by fran-worley** [comment]
Would this not be covered by https://github.com/DockYard/ember-composable-helpers#contains ?

**Comment by Techn1x** [comment]
Yeah, you're right. I guess at the time I wasn't using composable helpers add-on or I didn't know about the array helper! And I figured is-in was probably more suited here.

For anyone coming across this issue later, just install that add-on and do this

```handlebars
{{contains messageType (array 'ignition_on' 'ignition_off' 'idling_start' 'idling_end')}}
```
