### ISSUE TITLE
New release - 2.1.0?

### ISSUE THREAD

**Issue by snewcomer** [jmurphyau/ember-truth-helpers#84]
Last release was Oct 2017.  Possible to get a minor release?  Thanks!

**Comment by BrianSipple** [comment]
To add to that, I think it's slightly confusing to have `is-empty` documented in the README when it's not yet available in the latest release. 

I'd happily open up an MR to clarify that -- but I wouldn't want to get in the way if just cutting a new release would be easier 😄.

**Comment by sivakumar-kailasam** [comment]
Spent a few mins before i realised that this was missing in the latest available release 😅 Can we help the next person by publishing a release 😄?

**Comment by stuartskelton** [comment]
haha I just fell victim to this as well.

I had to make my own, it would be nice to have this released.

**Comment by NindroidX** [comment]
Had the same problem.. A new release would be great!

**Comment by jmurphyau** [comment]
will do this today

**Comment by jmurphyau** [comment]
Done
