### ISSUE TITLE
Update Ember CLI Version

### ISSUE THREAD

**Issue by jmurphyau** [jmurphyau/ember-truth-helpers#9]

**Comment by rwjblue** [comment]
I believe this was resolved in https://github.com/jmurphyau/ember-truth-helpers/pull/16.

**Comment by Glavin001** [comment]
Who has merge access? Let's get #16 merged and then get ready for Ember-cli 1.13.6 (which is already out now).

**Comment by rwjblue** [comment]
@jmurphyau has access (owner of the repo).  

Ember CLI v1.13.6 has relatively few changes to the default blueprint (see [here](https://github.com/kellyselden/ember-addon-output/compare/v1.13.1...v1.13.6)), feel free to send a PR updating.

**Comment by Glavin001** [comment]
For some reason I thought #16 had not yet been merged. I was mistaken.

Thanks! I'll take a look. I am new to Ember-CLI and its addon structure so I'll see what I can do.

**Comment by jmurphyau** [comment]
Yep - this was resolved by #16 (:
